spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: test

---
spring:
  profiles: prod
  kafka:
    bootstrap-servers:
      - kafka.tacocloud.com:9092
      - kafka.tacocloud.com:9093
      - kafka.tacocloud.com:9093 # 클러스터의 여러 서버를 지정할 수 있음.